Добавил frappe

diff --git a/deploy/docker-compose.yaml b/deploy/docker-compose.yaml
--- a/deploy/docker-compose.yaml
+++ b/deploy/docker-compose.yaml
@@ -78,11 +78,215 @@ services:
       - NOIP_HOSTNAMES=all.ddnskey.com
     restart: unless-stopped
 
+  ebay_frappe_backend:
+    image: frappe/erpnext:v15.51.1
+    container_name: ebay_frappe_backend
+    networks:
+      - ebay_internal_network
+    deploy:
+      restart_policy:
+        condition: on-failure
+    volumes:
+      - frappe_sites:/home/frappe/frappe-bench/sites
+      - ./mount/frappe/logs/:/home/frappe/frappe-bench/logs
+    environment:
+      DB_HOST: ebay_frappe_db
+      DB_PORT: "3306"
+      MYSQL_ROOT_PASSWORD: $PG_PASSWORD
+      MARIADB_ROOT_PASSWORD: $PG_PASSWORD
+
+  ebay_frappe_create-site:
+    image: frappe/erpnext:v15.51.1
+    container_name: ebay_frappe_create-site
+    networks:
+      - ebay_internal_network
+    deploy:
+      restart_policy:
+        condition: none
+    environment:
+      DB_HOST: ebay_frappe_db
+      DB_PORT: "3306"
+      REDIS_CACHE: ebay_frappe_redis-cache:6379
+      REDIS_QUEUE: ebay_frappe_redis-queue:6379
+      SOCKETIO_PORT: "9000"
+      DB_PASSWORD: $PG_PASSWORD
+      ADMIN_PASSWORD: $PG_PASSWORD
+    volumes:
+      - frappe_sites:/home/frappe/frappe-bench/sites
+      - ./mount/frappe/logs/:/home/frappe/frappe-bench/logs
+    entrypoint:
+      - bash
+      - -c
+    command:
+      - >
+        ls -1 apps > sites/apps.txt;
+        bench set-config -g db_host $$DB_HOST;
+        bench set-config -gp db_port $$DB_PORT;
+        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
+        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
+        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
+        bench set-config -gp socketio_port $$SOCKETIO_PORT;
+        wait-for-it -t 120 ebay_frappe_db:3306;
+        wait-for-it -t 120 ebay_frappe_redis-cache:6379;
+        wait-for-it -t 120 ebay_frappe_redis-queue:6379;
+        export start=`date +%s`;
+        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+        do
+          echo "Waiting for sites/common_site_config.json to be created";
+          sleep 5;
+          if (( `date +%s`-start > 120 )); then
+            echo "could not find sites/common_site_config.json with required keys";
+            exit 1
+          fi
+        done;
+        echo "sites/common_site_config.json found";
+        bench new-site --mariadb-user-host-login-scope='%' --admin-password=$$ADMIN_PASSWORD --db-root-username=root --db-root-password=$$DB_PASSWORD --set-default ebay_frappe_frontend;
+
+  ebay_frappe_db:
+    image: mariadb:10.6
+    container_name: ebay_frappe_db
+    networks:
+      - ebay_internal_network
+    healthcheck:
+      test: mysqladmin ping -h localhost --password=$PG_PASSWORD
+      interval: 1s
+      retries: 20
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - --character-set-server=utf8mb4
+      - --collation-server=utf8mb4_unicode_ci
+      - --skip-character-set-client-handshake
+      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
+    environment:
+      MYSQL_ROOT_PASSWORD: $PG_PASSWORD
+      MARIADB_ROOT_PASSWORD: $PG_PASSWORD
+    volumes:
+      - frappe_db_data:/var/lib/mysql
+
+  ebay_frappe_frontend:
+    image: frappe/erpnext:v15.51.1
+    container_name: ebay_frappe_frontend
+    networks:
+      - ebay_internal_network
+    depends_on:
+      - ebay_frappe_websocket
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - nginx-entrypoint.sh
+    environment:
+      BACKEND: ebay_frappe_backend:8000
+      FRAPPE_SITE_NAME_HEADER: ebay_frappe_frontend
+      SOCKETIO: ebay_frappe_websocket:9000
+      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
+      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
+      UPSTREAM_REAL_IP_RECURSIVE: "off"
+      PROXY_READ_TIMEOUT: 120
+      CLIENT_MAX_BODY_SIZE: 50m
+    volumes:
+      - frappe_sites:/home/frappe/frappe-bench/sites
+      - ./mount/frappe/logs/:/home/frappe/frappe-bench/logs
+    ports:
+      - "8080:8080"
+
+  ebay_frappe_queue-long:
+    image: frappe/erpnext:v15.51.1
+    container_name: ebay_frappe_queue-long
+    networks:
+      - ebay_internal_network
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - bench
+      - worker
+      - --queue
+      - long,default,short
+    volumes:
+      - frappe_sites:/home/frappe/frappe-bench/sites
+      - ./mount/frappe/logs/:/home/frappe/frappe-bench/logs
+
+  ebay_frappe_queue-short:
+    image: frappe/erpnext:v15.51.1
+    container_name: ebay_frappe_queue-short
+    networks:
+      - ebay_internal_network
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - bench
+      - worker
+      - --queue
+      - short,default
+    volumes:
+      - frappe_sites:/home/frappe/frappe-bench/sites
+      - ./mount/frappe/logs/:/home/frappe/frappe-bench/logs
+
+  ebay_frappe_redis-queue:
+    image: redis:6.2-alpine
+    container_name: ebay_frappe_redis-queue
+    networks:
+      - ebay_internal_network
+    deploy:
+      restart_policy:
+        condition: on-failure
+    volumes:
+      - redis-queue-data:/data
+
+  ebay_frappe_redis-cache:
+    image: redis:6.2-alpine
+    container_name: ebay_frappe_redis-cache
+    networks:
+      - ebay_internal_network
+    deploy:
+      restart_policy:
+        condition: on-failure
+
+  ebay_frappe_scheduler:
+    image: frappe/erpnext:v15.51.1
+    container_name: ebay_frappe_scheduler
+    networks:
+      - ebay_internal_network
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - bench
+      - schedule
+    volumes:
+      - frappe_sites:/home/frappe/frappe-bench/sites
+      - ./mount/frappe/logs/:/home/frappe/frappe-bench/logs
+
+  ebay_frappe_websocket:
+    image: frappe/erpnext:v15.51.1
+    container_name: ebay_frappe_websocket
+    networks:
+      - ebay_internal_network
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - node
+      - /home/frappe/frappe-bench/apps/frappe/socketio.js
+    volumes:
+      - frappe_sites:/home/frappe/frappe-bench/sites
+      - ./mount/frappe/logs/:/home/frappe/frappe-bench/logs
+
+
 networks:
   ebay_internal_network:
     driver: bridge
 
 volumes:
+  frappe_sites:
+  frappe_db_data:
   pgdata:
+  redis-queue-data:
   ebay_helper_keys:
   portainer_data:
